// Test script to simulate Stripe webhook events locally
// Run: npm run test:stripe-webhook or tsx src/scripts/test-stripe-webhook.ts

require('dotenv').config({ path: '.env.local' });
import { connectDB } from '../lib/mongodb';
import Member from '../models/Member';
import Donation from '../models/Donation';
import Order from '../models/Order';
import EventRegistration from '../models/EventRegistration';

// Simulate a Stripe payment_intent.succeeded event
async function simulateStripeWebhook() {
  try {
    await connectDB();
    console.log('🔗 Connected to database\n');

    // Get a test member/donation/order from database
    const testMember = await Member.findOne({ paymentStatus: 'pending' });
    const testDonation = await Donation.findOne({ status: 'pending' });
    const testOrder = await Order.findOne({ paymentStatus: 'pending' });
    const testRegistration = await EventRegistration.findOne({ paymentStatus: 'pending' });

    if (!testMember && !testDonation && !testOrder && !testRegistration) {
      console.log('⚠️  No pending payments found in database.');
      console.log('   Create a test membership/donation/order first.\n');
      return;
    }

    // Simulate webhook payload
    const webhookPayload = {
      id: `evt_test_${Date.now()}`,
      type: 'payment_intent.succeeded',
      data: {
        object: {
          id: testMember?.paymentId || testDonation?.paymentId || testOrder?.paymentId || testRegistration?.paymentId || 'pi_test_123',
          amount: testMember?.amount || testDonation?.amount || testOrder?.total || testRegistration?.totalPrice || 5000,
          currency: 'usd',
          status: 'succeeded',
          metadata: {
            type: testMember ? 'membership' : testDonation ? 'donation' : testOrder ? 'order' : 'event_registration',
            memberId: testMember?._id.toString(),
            donationId: testDonation?._id.toString(),
            orderId: testOrder?._id.toString(),
            registrationId: testRegistration?._id.toString()
          },
          receipt_email: testMember?.email || testDonation?.donorEmail || testOrder?.customerInfo?.email || testRegistration?.attendeeEmail
        }
      }
    };

    console.log('📤 Simulating Stripe webhook event...\n');
    console.log('Event Type:', webhookPayload.type);
    console.log('Payment Intent ID:', webhookPayload.data.object.id);
    console.log('Amount:', webhookPayload.data.object.amount / 100, webhookPayload.data.object.currency);
    console.log('Metadata:', webhookPayload.data.object.metadata);
    console.log('');

    // Make actual webhook call to local endpoint
    const baseUrl = process.env.NEXTAUTH_URL || 'http://localhost:3000';
    const response = await fetch(`${baseUrl}/api/webhooks/stripe`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'stripe-signature': 'test_signature' // In real scenario, this would be generated by Stripe
      },
      body: JSON.stringify(webhookPayload)
    });

    const result = await response.json();
    
    if (response.ok) {
      console.log('✅ Webhook processed successfully');
      console.log('Response:', result);
    } else {
      console.log('❌ Webhook processing failed');
      console.log('Error:', result);
    }

    // Check database status
    if (testMember) {
      await testMember.populate('paymentMethod');
      // const refreshedMember = await Member.findById(testMember._id); // Unused for now
      console.log('\n📊 Member Status:');
      console.log('  Payment Status:', testMember.paymentStatus);
      console.log('  Member Status:', testMember.status);
      console.log('  Is Active:', testMember.isActive);
    }

    if (testDonation) {
      await testDonation.reload();
      console.log('\n📊 Donation Status:');
      console.log('  Status:', testDonation.status);
    }

    if (testOrder) {
      await testOrder.reload();
      console.log('\n📊 Order Status:');
      console.log('  Payment Status:', testOrder.paymentStatus);
      console.log('  Order Status:', testOrder.status);
    }

    if (testRegistration) {
      await testRegistration.reload();
      console.log('\n📊 Registration Status:');
      console.log('  Payment Status:', testRegistration.paymentStatus);
      console.log('  Status:', testRegistration.status);
    }

  } catch (error) {
    console.error('❌ Error simulating webhook:', error);
    if (error instanceof Error) {
      console.error('Error message:', error.message);
    }
  } finally {
    process.exit(0);
  }
}

// Run simulation
simulateStripeWebhook();







